# Generated by Django 5.2.17 on 2026-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='has_setlist',
            field=models.BooleanField(default=True),
        ),
    ]
